#!/bin/env bash
#Getting apache to run on the container and to return a page containing Hello Holberton when querying the root of it.
echo "Holberton School" > /var/www/html/index.html
service apache2 start 
