#!/usr/bin/env bash 
# reacring to different types of signes
echo $$ > /var/run/holbertonscript.pid
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/holbertonscript.pid; echo 'I hate the kill command'; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
while :
do
echo "To infinity and beyond"
sleep 2
done 

