#!/usr/bin/env bash 
# this script manages the manage_my_process
startt() {
./manage_my_process &
echo "$!" > /var/run/holbertonscript.pid
}
stopp() {
pkill -f "./manage_my_process"
rm /var/run/holbertonscript.pid
}
restartt() {
stopp
startt
echo "manage_my_process restarted"
}
case "$1" in 
	start)
	echo "manage_my_process started"
	startt
	;;
	stop)
	echo "manage_my_process stopped"
	stopp
	;;
	restart)
	restartt
	;;
	*) 
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
