#!/usr/bin/env bash
# clock that displays the time hours from 0-12 and minutes from 1-59
h=0
m=0
while [ $h -le 13 ]; do 
if [[ $h -eq 0 ]]; then 
echo "Hour: $h"
((h=h+1))
elif [[ $m -ne 59 ]]; then
((m=m+1))
echo $m 
else
if [[ $h -lt 13 ]]; then
echo "Hour: $h"
fi  
((h=h+1))
((m=0))
fi 
done
 
