#!/usr/bin/env bash 
#testing if a file exists or not 
FILE="holbertonschool"
if test -e "$FILE"; then 
    echo "holbertonschool file exists"
    if test -f "$FILE";then
        echo "holbertonschool is a regular file"
    if [[ -s $FILE ]]; then 
        echo "holbertonschool file is not empty"
    else 
        echo "holbertonschool file is empty"
    fi
    
else 
    echo "holbertonschool file does not exist" 
fi   
