#!/usr/bin/env bash
#installing and configuring haproxy with roundrobin algorithm
ROUDALGO="backend web_servers \n
        \tmode http\n
	\tbalance roundrobin\n
        \tserver web-02 35.185.51.133:80 check\n
        \tserver web-01 34.73.106.157:80 check\n"
apt-get update 
apt-get -y install 
echo "ENABLED=1" >> /etc/default/haproxy
echo $ROUNDALGO >> /etc/haproxy/haproxy.cfg
service haproxy restart

