#!/usr/bin/env bash
#installing and configuring haproxy with roundrobin algorithm
ROUNDALGO_BACK="backend web_back\n
        \tbalance roundrobin\n
	\tserver 3118-web-02 35.185.51.133:80 check\n
	\tserver 3118-web-01 34.73.106.157:80 check\n"
ROUNDALGO_FRONT="frontend web_front\n
		\tbind *:80\n
		\tmode http\n
		\tdefault_backend web_back\n"
apt-get -y update 
apt-get -y install haproxy 
echo 'ENABLED=1' >> /etc/default/haproxy
echo -e $ROUNDALGO_FRONT>> /etc/haproxy/haproxy.cfg
echo -e $ROUNDALGO_BACK >> /etc/haproxy/haproxy.cfg
service haproxy restart

