#!/usr/bin/env bash 
#configuring domain zone and ignoring shellcheck SC2086

disp ()
{
    DOMAIN="$1"
    SUBDOMAIN="$2"
    dig "$SUBDOMAIN.$DOMAIN" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$SUBDOMAIN"
}

for SUBDOMAIN in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$SUBDOMAIN" ] ;
    then
	disp "$1" "$SUBDOMAIN"
    fi
done
