#!/usr/bin/env bash 
#configuring domain zone and ignoring shellcheck SC2086

CONF_DOMAIN () {
echo "void"
}
if [ $# -eq 1 ]; then 
   for SUBDOMAIN in 'www' 'lb-01' 'web-01' 'web-02'
    do
        URL="$SUBDOMAIN.$1"
        IPADD=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
        TYPE=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
        echo "The subdomain $SUBDOMAIN is a $TYPE record and points to $IPADD"
    done
elif [ $# -eq 2 ]; then 
    URL="$2.$1"
    IPADD=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    TYPE=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    echo "The subdomain $2 is a $RECORDTYPE record and points to $IPADD"
fi
