#!/usr/bin/env bash
#configuring nginx server to /redirect_me to another page.
$MYGITHUB="https://github.com/OussamaAlaoui"
apt-get -y update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
echo Holberton School > /var/www/html/index.nginx-debian.htmli
mkdir -p /var/www/redirect_me/html
echo "This is a file for our redirection project." > /var/www/redirect_me/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/redirect_me
sed -i 's/^listen/listen 80;/' /etc/nginx/sites-available/redirect_me
sed -i 's/root .*/root \/var\/www\/redirect_me\/html;/' /etc/nginx/sites-available/redirect_me 
sed -i 's/^server_name .*/server_name redirect_me;/' /etc/nginx/sites-available/redirect_me
sed -i '42irewrite ^/(.*)$ $MYGITHUB permanent;'
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
service nginx restart
