#!/usr/bin/env bash
#configuring nginx server to /redirect_me to another page.
MYGITHUB=" rewrite ^/(.*)$ https://github.com/OussamaAlaoui/emsi-devops/blob/main/0x02-web_server/3-redirection permanent;\n"
apt-get update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "37i $MYGITHUB" /etc/nginx/sites-available/default
service nginx restart
