#!/usr/bin/env bash
#configuring nginx server to /redirect_me to another page.
$MYGITHUB="\\\tlocation /redirect_me {\n\t\t return 301 https://github.com/OussamaAlaoui;\n\t}\n"
apt-get update
apt-get -y install nginx
echo "This is a file for our redirection project." | tee /usr/share/nginx/html/index.html
sed -i '30i $MYGITHUB' /etc/nginx/sites-available/default
service nginx restart
