#!/usr/bin/env bash
# returning a special 404 Error
CUSTOM_404="error_page 404 /ERROR404.html;\n\t location = /ERROR404.html {\nroot /usr/share/nginx;\ninternal;\n}\n"
apt-get update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/ERROR404.html
sed -i "25i $CUSTOM_404" /etc/nginx/sites-available/default
service nginx restart
