#!/usr/bin/env bash
# returning a special 404 Error
CUSTOM_404="\\\terror_page 404 /ERROR404.html;\n\t location = /ERROR404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
MYGITHUB="\\\tlocation /redirect_me {\n\t\t return 301 https://github.com/OussamaAlaoui;\n\t}\n"
ERROR_PATH="#error_page 404 /ERROR404.html;"
ufw allow 'Nginx HTTP'
apt-get update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "49i $MYGITHUB" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/ERROR404.html
sed -i "s@$ERROR_PATH@$CUSTOM_404@" /etc/nginx/sites-available/default
service nginx restart
